"""Every experiment that ran, including the ones nobody wants to remember.

This is the whole anti-overfitting mechanism, and it is a counter rather than a prohibition.
Nobody can be stopped from looking at the same question a twentieth time; what can be arranged
is that the twentieth look is on the record, so a result reached on the last attempt cannot be
presented as though it were the first.

Two absences are deliberate. Nothing here deletes or replaces — re-running an experiment adds
a line, and the same identifier appearing repeatedly *is* the finding. And there is no
``best``, no ``rank`` and no ``top``: the distance between "the harness can order these by
profit" and "the harness says this one is good" is one habit, and the honest place to close
that distance is before the method exists.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from enum import StrEnum
from pathlib import Path

from pydantic import Field

from quantplatform.core.models.base import DomainModel, Text, UtcDatetime
from quantplatform.research.result import ExperimentResult, ExperimentStatus, result_hash
from quantplatform.research.store import ResultStore, attempt_id

_ENTRY_ID_LENGTH = 32

__all__ = [
    "ExperimentLedger",
    "LedgerEntry",
    "ReproducibilityVerdict",
    "VariationKind",
    "verify",
]


class VariationKind(StrEnum):
    """Which protocol generated a run, when one did.

    Lives here, next to :class:`LedgerEntry`, rather than in
    :mod:`quantplatform.research.robustness`: the alternative would have ``ledger`` import
    from ``robustness`` for this enum while ``robustness`` imports :class:`LedgerEntry` from
    ``ledger`` for :class:`~quantplatform.research.robustness.VariationRun` — a cycle. This
    enum is metadata about a ledger line, so it belongs with the line.
    """

    SENSITIVITY = "sensitivity"
    REGIME = "regime"
    STRESS = "stress"


class LedgerEntry(DomainModel):
    """One line of the record: an experiment ran, and this is what came of it."""

    entry_id: Text
    """This line's own name, derived from its contents, so a verdict can point at what it
    contradicts."""

    experiment_id: Text
    attempt_id: Text
    """The stored result this line describes. Written before the line, so a ledger entry never
    points at evidence that does not exist."""

    name: Text
    result_hash: Text
    bars_digest: Text | None = None
    """Fingerprint of the data the run consumed, or ``None`` for a line written before this
    field existed. Its absence is why :func:`verify` can answer "I cannot tell"."""

    code_revision: Text | None = None
    status: ExperimentStatus
    recorded_at: UtcDatetime
    plan_id: Text | None = None
    """Walk-forward plan this run belonged to, when it belonged to one.

    Lineage lives here rather than in the definition: which plan a window was run under is
    *why* it was run, not *what* was run, so the same window run alone and run inside a plan
    keeps one identity and gains two records.
    """

    fold_index: int | None = Field(default=None, ge=0)
    verdict: ReproducibilityVerdict | None = None
    """What comparing this run with a previous one established, or ``None`` on the first run
    of an experiment — where there is nothing to compare and nothing is pretended.

    Recorded on every line, so ``DATASET_CHANGED``, ``CODE_CHANGED`` and ``INDETERMINATE``
    stay visible without raising an alarm: they are information, not accusations.
    """

    compared_with: Text | None = None
    """The line this verdict disagrees with, on a reproducibility failure.

    A violation is *appended*, naming what it contradicts. Nothing earlier is edited: the
    record of what was believed at the time is itself evidence.
    """

    derived_from: Text | None = None
    """The ``experiment_id`` of the base experiment this run was generated from, when it was
    generated by a sensitivity, regime or stress protocol.

    Lives here rather than in the definition, for the same reason ``plan_id`` does: *why* a
    run happened is not *what* ran. ``None`` for a standalone run, and for the base run of a
    sensitivity or stress plan itself — the base was not derived from anything, it IS the
    thing everything else is derived from.
    """

    variation_kind: VariationKind | None = None
    """Which protocol produced this run, or ``None`` for a standalone run or a walk-forward
    fold — those already have ``plan_id``/``fold_index`` for their own lineage."""

    variation_plan_id: Text | None = None
    """Which :class:`~quantplatform.research.sensitivity.SensitivityPlan`,
    :class:`~quantplatform.research.regime.RegimePlan` or
    :class:`~quantplatform.research.stress.StressPlan` this run belongs to — the batch
    identifier, analogous to ``plan_id`` for walk-forward. Lets every run one invocation
    produced be grouped and re-listed later without reconstructing the sweep."""


class ExperimentLedger:
    """An append-only record of every experiment attempted."""

    def __init__(self, path: Path) -> None:
        """Point a ledger at its file, which need not exist yet.

        Args:
            path: JSON-lines file the record is appended to. Never rewritten.
        """
        self._path = path

    def record(
        self,
        result: ExperimentResult,
        *,
        store: ResultStore | None = None,
        plan_id: str | None = None,
        fold_index: int | None = None,
        derived_from: str | None = None,
        variation_kind: VariationKind | None = None,
        variation_plan_id: str | None = None,
    ) -> LedgerEntry:
        """Store the result, append it to the record, and say whether it contradicts anything.

        The order matters and is the whole of the safety here. The evidence is written first,
        so a ledger line can never name a result that was never stored; then the line; then
        the comparison. A verdict that could prevent a result from being recorded would be a
        checker with the power to erase what it disagrees with.

        Failures are recorded exactly like successes. An experiment that blew up is evidence
        about the configuration that blew it up, and a record holding only what worked would
        describe a platform that never had a bad idea.

        Args:
            result: What to record.
            store: Where the result itself is kept. Optional only so that a caller holding an
                already-stored attempt can pass its identifier instead.
            plan_id: Walk-forward plan this run belonged to, when it belonged to one.
            fold_index: Its position in that plan.
            derived_from: The base experiment this run was generated from, when a sensitivity,
                regime or stress protocol generated it.
            variation_kind: Which of those three protocols generated this run.
            variation_plan_id: Which plan of that protocol this run belongs to.

        Returns:
            The line written for this result. A contradiction appends a second line after it,
            which :meth:`entries` will show.
        """
        identifier = store.save(result) if store is not None else attempt_id(result)
        previous = [
            entry for entry in self.entries() if entry.experiment_id == result.experiment_id
        ]
        entry = self._build_entry(
            result,
            attempt=identifier,
            plan_id=plan_id,
            fold_index=fold_index,
            derived_from=derived_from,
            variation_kind=variation_kind,
            variation_plan_id=variation_plan_id,
            verdict=None,
            status=result.status,
            compared_with=None,
        )
        against = _comparable(previous, entry)
        if against is not None:
            entry = self._build_entry(
                result,
                attempt=identifier,
                plan_id=plan_id,
                fold_index=fold_index,
                derived_from=derived_from,
                variation_kind=variation_kind,
                variation_plan_id=variation_plan_id,
                verdict=verify(against, entry),
                status=result.status,
                compared_with=None,
            )
        self._append(entry)
        if entry.verdict is ReproducibilityVerdict.REPRODUCIBILITY_FAILURE and against is not None:
            self._append(
                self._build_entry(
                    result,
                    attempt=identifier,
                    plan_id=plan_id,
                    fold_index=fold_index,
                    derived_from=derived_from,
                    variation_kind=variation_kind,
                    variation_plan_id=variation_plan_id,
                    verdict=ReproducibilityVerdict.REPRODUCIBILITY_FAILURE,
                    status=ExperimentStatus.REPRODUCIBILITY_FAILURE,
                    compared_with=against.entry_id,
                )
            )
        return entry

    def _build_entry(  # noqa: PLR0913 - a ledger line is defined by exactly these inputs
        self,
        result: ExperimentResult,
        *,
        attempt: str,
        plan_id: str | None,
        fold_index: int | None,
        derived_from: str | None,
        variation_kind: VariationKind | None,
        variation_plan_id: str | None,
        verdict: ReproducibilityVerdict | None,
        status: ExperimentStatus,
        compared_with: str | None,
    ) -> LedgerEntry:
        """Assemble one line and give it the name its own contents imply."""
        fields: dict[str, object] = {
            "experiment_id": result.experiment_id,
            "attempt_id": attempt,
            "name": result.definition.name,
            "result_hash": result_hash(result),
            "bars_digest": result.bars_digest,
            "code_revision": result.code_revision,
            "plan_id": plan_id,
            "fold_index": fold_index,
            "derived_from": derived_from,
            "variation_kind": variation_kind,
            "variation_plan_id": variation_plan_id,
            "verdict": verdict,
            "compared_with": compared_with,
            "status": status,
            "recorded_at": result.finished_at,
        }
        return LedgerEntry(entry_id=_entry_id(fields), **fields)  # type: ignore[arg-type]

    def _append(self, entry: LedgerEntry) -> None:
        """Write one line. Never rewrites, never reorders."""
        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as handle:
            handle.write(entry.model_dump_json() + "\n")

    def entries(self) -> tuple[LedgerEntry, ...]:
        """Return every line ever appended, oldest first."""
        if not self._path.exists():
            return ()
        return tuple(
            LedgerEntry.model_validate(json.loads(line))
            for line in self._path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        )

    def attempts(self, experiment_id: str) -> int:
        """Return how many times this exact experiment has been run.

        The number a reader needs before believing any single result: an outcome found on the
        first attempt and one found on the twelfth are different kinds of evidence, and only
        this count distinguishes them.
        """
        return len(self.attempts_for(experiment_id))

    def attempts_for(self, experiment_id: str) -> tuple[LedgerEntry, ...]:
        """Return every real attempt at this experiment, oldest first.

        A ``REPRODUCIBILITY_FAILURE`` line is not a second look at the question: it
        *restates* an attempt already on this list to raise an alarm about it, sharing that
        attempt's own ``attempt_id``. Counting it as a third attempt would overstate how many
        times the question was actually asked, exactly when a contradiction is already the
        thing most likely to mislead a reader who skims the count.
        """
        return tuple(
            entry
            for entry in self.entries()
            if entry.experiment_id == experiment_id and _is_a_real_attempt(entry)
        )

    def latest_attempt(self, experiment_id: str) -> LedgerEntry:
        """Return the most recent real attempt at this experiment.

        Raises:
            LookupError: If the experiment never ran. Answering with an empty or synthetic
                entry would let a caller compare against a run that never happened.
        """
        attempts = self.attempts_for(experiment_id)
        if not attempts:
            msg = f"experiment {experiment_id} never ran"
            raise LookupError(msg)
        return attempts[-1]

    def entry_for_attempt(self, attempt_id: str) -> LedgerEntry:
        """Return the line that first recorded this attempt.

        Raises:
            LookupError: If no line names this attempt. A ``compare`` asking for a specific
                attempt is asking about a specific run, and a run that was never recorded is
                a question with no evidence to answer it, not zero rows.
        """
        for entry in self.entries():
            if entry.attempt_id == attempt_id and _is_a_real_attempt(entry):
                return entry
        msg = f"no recorded attempt {attempt_id}"
        raise LookupError(msg)

    def entries_derived_from(self, experiment_id: str) -> tuple[LedgerEntry, ...]:
        """Return every run generated from this base experiment, oldest first.

        Every sensitivity variant, regime episode or stress scenario derived from a base
        names it via ``derived_from`` — this is how a reader finds them all again without
        reconstructing the sweep that produced them.
        """
        return tuple(entry for entry in self.entries() if entry.derived_from == experiment_id)

    def entries_in_variation_plan(self, variation_plan_id: str) -> tuple[LedgerEntry, ...]:
        """Return every run belonging to this sensitivity, regime or stress plan, oldest first.

        Includes the plan's own baseline run only if the baseline itself was recorded with
        this ``variation_plan_id`` — a base run's own entry carries ``derived_from=None``
        because it is not derived from anything, but a caller that wants it grouped with its
        variants under one plan passes this same ``variation_plan_id`` when recording it too.
        """
        return tuple(
            entry for entry in self.entries() if entry.variation_plan_id == variation_plan_id
        )


class ReproducibilityVerdict(StrEnum):
    """What comparing two runs of one experiment establishes."""

    INDETERMINATE = "indeterminate"
    DATASET_CHANGED = "dataset_changed"
    CODE_CHANGED = "code_changed"
    REPRODUCIBLE = "reproducible"
    REPRODUCIBILITY_FAILURE = "reproducibility_failure"


def verify(earlier: LedgerEntry, later: LedgerEntry) -> ReproducibilityVerdict:
    """Return what two runs of the same experiment establish about each other.

    Asked in a fixed order, and the order is the argument. **Indeterminate comes first**:
    without both fingerprints nothing can be concluded, and answering "the dataset changed"
    with no digest to compare would be inventing a finding rather than reporting one. Lines
    written before those fields existed land here, which is the honest place for them.

    A disagreement is only alarming when nothing else moved. Different data explains a
    different result, and so does different code; calling either irreproducible would blame
    the engine for its inputs and would cry wolf until nobody read the verdicts. Data is
    checked before code because a changed dataset makes the code comparison moot.

    Args:
        earlier: The line recorded first.
        later: The line to compare against it.

    Returns:
        The verdict.

    Raises:
        ValueError: If the two lines are not the same experiment, which is a programming
            error rather than a finding — there is nothing to conclude from comparing two
            different questions.
    """
    if earlier.experiment_id != later.experiment_id:
        msg = "reproducibility is only meaningful between runs of the same experiment"
        raise ValueError(msg, {"earlier": earlier.experiment_id, "later": later.experiment_id})
    fingerprints = (
        earlier.bars_digest,
        later.bars_digest,
        earlier.code_revision,
        later.code_revision,
    )
    if any(value is None for value in fingerprints):
        return ReproducibilityVerdict.INDETERMINATE
    if earlier.bars_digest != later.bars_digest:
        return ReproducibilityVerdict.DATASET_CHANGED
    if earlier.code_revision != later.code_revision:
        return ReproducibilityVerdict.CODE_CHANGED
    if earlier.result_hash == later.result_hash:
        return ReproducibilityVerdict.REPRODUCIBLE
    return ReproducibilityVerdict.REPRODUCIBILITY_FAILURE


def _entry_id(fields: Mapping[str, object]) -> str:
    """Return a line's name, derived from everything in it except the name itself."""
    payload = "|".join(f"{key}={fields[key]!s}" for key in sorted(fields))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:_ENTRY_ID_LENGTH]


def _is_a_real_attempt(entry: LedgerEntry) -> bool:
    """Return whether this line is a run rather than an alarm restating one.

    A ``REPRODUCIBILITY_FAILURE`` line shares its ``attempt_id`` with the attempt it is
    raising an alarm about — it names no evidence of its own. Shared by every place that
    counts, lists or looks up attempts, so "what counts as an attempt" is answered once.
    """
    return entry.status is not ExperimentStatus.REPRODUCIBILITY_FAILURE


def _comparable(previous: Sequence[LedgerEntry], entry: LedgerEntry) -> LedgerEntry | None:
    """Return the earlier run this one should be judged against.

    The most recent attempt that shares both fingerprints, because that is the comparison
    capable of accusing the engine. Only when no such attempt exists does it fall back to the
    most recent line, and then purely to report *why* the two are not comparable — running A,
    then B, then A again would otherwise answer "the code changed" and quietly bury the
    contradiction with the first A.

    Attempts that were themselves alarms are skipped: an alarm restates a result rather than
    adding one, and comparing against it would count the same run twice.
    """
    candidates = [line for line in previous if _is_a_real_attempt(line)]
    if not candidates:
        return None
    matched = [
        line
        for line in candidates
        if line.bars_digest == entry.bars_digest and line.code_revision == entry.code_revision
    ]
    return matched[-1] if matched else candidates[-1]
